export VAULT_ADDR='http://127.0.0.1:8201'
export VAULT_AUTHTYPE=userpass
export VAULT_USER='portugal'
export VAULT_PASSWORD='Th3m@n!!'
unset VAULT_LOGIN_MOUNT_POINT
unset VAULT_ROLE_ID
unset VAULT_SECRET_ID
unset VAULT_TOKEN
unset VAULT_KEYS
