---
- hosts: localhost
  gather_facts: no
  vars:
    username: 'portugal_idempotent'
    userpass: 'Th3m@n!!'
  tasks:
    - name: Enable kv2 secret store
      hashivault_userpass:
        name: bob
        state: absent
      no_log: True

    - name: Enable kv2 secret store
      hashivault_userpass:
        name: bob
        pass: S3cre7s
        policies: bob
      register: hashivault_userpass
      no_log: True
    - assert: { that: "hashivault_userpass is changed" }
    - assert: { that: "hashivault_userpass.rc == 0" }

    - name: Set token_bound_cidr for userpass
      hashivault_userpass:
        name: "{{username}}"
        pass: "{{userpass}}"
        policies: "default"
        token_bound_cidrs: "127.0.0.1"
      register: 'hashivault_userpass_token_bound_cidr'
    - assert: { that: "hashivault_userpass_token_bound_cidr is changed" }
    - assert: { that: "hashivault_userpass_token_bound_cidr.rc == 0" }

    - name: Set token_bound_cidr for userpass (idempotent)
      hashivault_userpass:
        name: "{{username}}"
        pass: "{{userpass}}"
        policies: "default"
        token_bound_cidrs: "127.0.0.1"
      register: 'hashivault_userpass_token_bound_cidr'
    - assert: { that: "hashivault_userpass_token_bound_cidr is not changed" }
    - assert: { that: "hashivault_userpass_token_bound_cidr.rc == 0" }
