---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: arrange - policies - functional_testing_policy_one
      hashivault_policy:
        name: functional_testing_policy_one
        rules: 'path "secret/*" {capabilities = ["read", "list"]}'

    - name: arrange - policies - functional_testing_policy_two
      hashivault_policy:
        name: functional_testing_policy_two
        rules: 'path "secret/*" {capabilities = ["read", "list"]}'

    - name: enable ldap authentication
      hashivault_auth_method:
        method_type: ldap

    - name: ldap configuration
      hashivault_auth_ldap:
        ldap_url: ldap://localhost
      register: ldap_module
    - assert: { that: "{{ ldap_module.changed }} == True" }
    - assert: { that: "{{ ldap_module.rc }} == 0" }

    - name: ldap configuration is idempotent
      hashivault_auth_ldap:
        ldap_url: ldap://localhost
      register: ldap_module_idempotent
    - assert: { that: "{{ ldap_module_idempotent.changed }} == False" }

    - name: remove ldap group
      hashivault_ldap_group:
        name: test
        state: absent

    - name: add ldap group
      hashivault_ldap_group:
        name: test
        state: present
      register: success_config

    - assert: { that: "{{ success_config.changed }} == True" }

    - name: chg policies - add functional_testing_policy_one
      hashivault_ldap_group:
        name: test
        state: present
        policies:
          - functional_testing_policy_one
      register: chg_policies

    - assert: { that: "{{ chg_policies.changed }} == True" }

    - name: duplicate policies
      hashivault_ldap_group:
        name: test
        state: present
        policies:
          - functional_testing_policy_one
      register: chg_policies

    - assert: { that: "{{ chg_policies.changed }} == False" }

    - name: chg policies - add functional_testing_policy_two
      hashivault_ldap_group:
        name: test
        state: present
        policies:
          - functional_testing_policy_one
          - functional_testing_policy_two
      register: chg_policies

    - assert: { that: "{{ chg_policies.changed }} == True" }

    - name: chg policies - remove functional_testing_policy_one
      hashivault_ldap_group:
        name: test
        state: present
        policies:
          - functional_testing_policy_two
      register: chg_policies

    - assert: { that: "{{ chg_policies.changed }} == True" }
