---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: create token role check_mode exists
      hashivault_token_role:
        name: testrole
        config:
          allowed_policies:
            - tokenrole_test_policy
        state: present
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "vault_role_create is not changed" }
    - assert: { that: "vault_role_create.rc == 0" }

    - name: create token role check_mode does not exist
      hashivault_token_role:
        name: testrole_two
        config:
          allowed_policies:
            - tokenrole_test_policy
        state: present
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "vault_role_create is changed" }
    - assert: { that: "vault_role_create.rc == 0" }

    - name: delete token role check_mode exists
      hashivault_token_role:
        name: testrole
        state: absent
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "vault_role_create is changed" }
    - assert: { that: "vault_role_create.rc == 0" }

    - name: delete token role check_mode does not exist
      hashivault_token_role:
        name: testrole_two
        state: absent
      check_mode: true
      register: 'vault_role_create'
    - assert: { that: "vault_role_create is not changed" }
    - assert: { that: "vault_role_create.rc == 0" }

    - name: list token roles check_mode
      hashivault_token_role_list:
      register: 'vault_role_list'
      check_mode: true
    - assert: { that: "vault_role_list is not changed" }
    - assert: { that: "vault_role_list.rc == 0" }
    - fail: msg="role testrole not in list {{vault_role_list.data}}"
      when: '"testrole" not in vault_role_list.data'
