---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: arrange - policies - functional_testing_policy_one
      hashivault_policy:
        name: functional_testing_policy_one
        rules: 'path "secret/*" {capabilities = ["read", "list"]}'

    - name: arrange - policies - functional_testing_policy_two
      hashivault_policy:
        name: functional_testing_policy_two
        rules: 'path "secret/*" {capabilities = ["read", "list"]}'

    - name: enable radius authentication
      hashivault_auth_method:
        method_type: radius

    - name: radius configuration
      hashivault_radius_config:
        host: localhost
        secret: test_secret
      register: radius_config
    - assert: { that: "radius_config is changed" }
    - assert: { that: "radius_config.rc == 0" }

    - name: remove radius user
      hashivault_radius_user:
        name: test
        state: absent

    - name: add radius user
      hashivault_radius_user:
        name: test
        state: present
      register: success_config

    - assert: { that: "success_config is changed" }

    - name: chg policies - add functional_testing_policy_one
      hashivault_radius_user:
        name: test
        state: present
        policies:
          - functional_testing_policy_one
      register: chg_policies

    - assert: { that: "chg_policies is changed" }

    - name: duplicate policies
      hashivault_radius_user:
        name: test
        state: present
        policies:
          - functional_testing_policy_one
      register: chg_policies

    - assert: { that: "chg_policies is not changed" }

    - name: chg policies - add functional_testing_policy_two
      hashivault_radius_user:
        name: test
        state: present
        policies:
          - functional_testing_policy_one
          - functional_testing_policy_two
      register: chg_policies

    - assert: { that: "chg_policies is changed" }

    - name: chg policies - remove functional_testing_policy_one
      hashivault_radius_user:
        name: test
        state: present
        policies:
          - functional_testing_policy_two
      register: chg_policies

    - assert: { that: "chg_policies is changed" }

    - name: delete radius user
      hashivault_radius_user:
        name: test
        state: absent
      register: delete_user

    - assert: { that: "delete_user is changed" }

    - name: delete already deleted radius user
      hashivault_radius_user:
        name: test
        state: absent
      register: delete_user_idempotent

    - assert: { that: "delete_user_idempotent is not changed" }
