---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: delete kv the first time
      hashivault_secret_engine:
        name: kvengine
        backend: kv
        state: disabled
    - name: create kv with seal_wrap
      hashivault_secret_engine:
        name: kvwrappedengine
        backend: kv
        state: disabled

    - name: create kv with seal_wrap
      hashivault_secret_engine:
        name: kvwrappedengine
        backend: kv
        state: enabled
        seal_wrap: True
      register: engine_result
    - assert: { that: "{{ engine_result.rc }} == 0" }
    - assert: { that: "{{ engine_result.created }} == True" }
    - assert: { that: "{{ engine_result.changed }} == True" }
    
    - name: create non-replicated kv
      hashivault_secret_engine:
        name: kvengine
        backend: kv
        state: enabled
        local: True
      register: engine_result
    - assert: { that: "{{ engine_result.rc }} == 0" }
    - assert: { that: "{{ engine_result.created }} == True" }
    - assert: { that: "{{ engine_result.changed }} == True" }