---
- hosts: localhost
  gather_facts: no
  vars:
    username: 'portugal'
    userpass: 'Th3m@n!!'
    rules: >
        path "secret/userpass/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
        } 
        path "secret/userpass" {
          capabilities = ["list"]
        } 
  tasks:
    - hashivault_auth_enable:
        name: "userpass"
      failed_when: False
    - hashivault_userpass_delete:
        name: "{{username}}"
    - hashivault_policy_delete:
        name: "{{username}}"

    - name: Set policy for userpass
      hashivault_policy_set:
        name: "{{username}}"
        rules: "{{rules}}"
      register: 'vault_policy_set'
    - assert: { that: "{{vault_policy_set.changed}} == True" }
    - assert: { that: "{{vault_policy_set.rc}} == 0" }

    - name: Create user pass with policy
      hashivault_userpass_create:
        name: "{{username}}"
        pass: "{{userpass}}"
        policies: "{{username}}"
      register: 'vault_userpass_create'
      no_log: True
    - assert: { that: "{{vault_userpass_create.changed}} == True" }
    - assert: { that: "{{vault_userpass_create.rc}} == 0" }

    - name: Create user to delete with policy
      hashivault_userpass_create:
        name: "delete_{{username}}"
        pass: "{{userpass}}"
        policies: "{{username}}"
      register: 'vault_userpass_create'
      no_log: True
    - assert: { that: "{{vault_userpass_create.changed}} == True" }
    - assert: { that: "{{vault_userpass_create.rc}} == 0" }

    - hashivault_userpass_delete:
        name: "delete_{{username}}"
      register: 'vault_userpass_delete'
    - assert: { that: "{{vault_userpass_delete.changed}} == True" }
    - assert: { that: "{{vault_userpass_delete.rc}} == 0" }

    - template:
        src: "{{playbook_dir}}/templates/userpassenv.sh.j2"
        dest: "{{playbook_dir}}/userpassenv.sh"
        mode: 0700
