---
- hosts: localhost
  gather_facts: no
  tasks:
    - hashivault_status:
      register: 'vault_status'
    - assert: { that: "{{vault_status.changed}} == False" }
    - assert: { that: "{{vault_status.rc}} == 0" }
