---
- hosts: localhost
  gather_facts: no
  tasks:
    - hashivault_secret_engine:
        name: dummyv2
        backend: kv
        options:
          version: 2
        state: present
    - hashivault_write:
        secret: 'listone'
        data:
            monday: 'one'
            tuesday: 'onetwo'
    - hashivault_write:
        secret: 'list/two'
        data:
          wednesday: 'threde'
    - hashivault_write:
        secret: 'listone'
        data:
            monday: 'one'
            tuesday: 'onetwo'
        version: 2
        mount_point: dummyv2
    - hashivault_write:
        secret: 'list/two'
        data:
          wednesday: 'threde'
        version: 2
        mount_point: dummyv2

    - name: Make sure we got our two secrets in list
      hashivault_list:
      register: vault_list
    - assert: { that: "vault_list.rc == 0" }
    - assert: { that: "'listone' in vault_list.secrets" }
    - assert: { that: "'list/' in vault_list.secrets" }

    - name: List secrets not in folder
      hashivault_list:
        secret: 'whatutalkinbout'
      register: vault_list
      failed_when: False
    - assert: { that: "vault_list.changed == False" }
    - assert: { that: "vault_list.rc == 1" }
    - assert: { that: "vault_list.msg == 'Secret does not exist: secret/whatutalkinbout'" }

    - name: List secrets in folder
      hashivault_list:
        secret: list
      register: vault_list
    - assert: { that: vault_list.rc == 0 }
    - assert: { that: "'two' in vault_list.secrets" }

    - name: List secrets in folder full path
      hashivault_list:
        secret: /secret/list
      register: vault_list
    - assert: { that: vault_list.rc == 0 }
    - assert: { that: "'two' in vault_list.secrets" }

    - hashivault_write:
        secret: 'list/second/level'
        data:
          wednesday: 'asdf'

    - name: List secrets in folder full path levels
      hashivault_list:
        secret: /secret/list/second
      register: vault_list
    - assert: { that: vault_list.rc == 0 }
    - assert: { that: "'level' in vault_list.secrets" }

    - name: Make sure we got our two secrets in list
      hashivault_list:
        mount_point: dummyv2
        version: 2
      register: vault_list
    - assert: { that: "vault_list.rc == 0" }
    - assert: { that: "'listone' in vault_list.secrets" }
    - assert: { that: "'list/' in vault_list.secrets" }

    - name: List secrets not in folder
      hashivault_list:
        secret: 'whatutalkinbout'
        mount_point: dummyv2
        version: 2
      register: vault_list
      failed_when: False
    - assert: { that: "vault_list.changed == False" }
    - assert: { that: "vault_list.rc == 1" }
    - assert: { that: "vault_list.msg == 'Secret does not exist: dummyv2/whatutalkinbout'" }

    - name: List secrets in folder
      hashivault_list:
        secret: list
        mount_point: dummyv2
        version: 2
      register: vault_list
    - assert: { that: vault_list.rc == 0 }
    - assert: { that: "'two' in vault_list.secrets" }
