---
- hosts: localhost
  gather_facts: no
  vars:
    username: 'portugal'
    userpass: 'Th3m@n!!'
    rules: >
        path "secret/userpass/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
        } 
        path "secret/userpass" {
          capabilities = ["list"]
        } 
  tasks:
    - hashivault_auth_method:
        method_type: "userpass"
      failed_when: False
    - hashivault_userpass:
        name: "{{username}}"
        state: absent
    - hashivault_policy:
        name: "{{username}}"
        state: absent

    - name: Set policy for userpass
      hashivault_policy:
        name: "{{username}}"
        rules: "{{rules}}"
      register: vault_policy
    - assert: { that: "{{vault_policy.changed}} == True" }
    - assert: { that: "{{vault_policy.rc}} == 0" }

    - name: Create user pass with policy
      hashivault_userpass:
        name: "{{username}}"
        pass: "{{userpass}}"
        policies: "{{username}}"
      register: 'vault_userpass_create'
      no_log: True
    - assert: { that: "{{vault_userpass_create.changed}} == True" }
    - assert: { that: "{{vault_userpass_create.rc}} == 0" }

    - name: Create user to delete with policy
      hashivault_userpass:
        name: "delete_{{username}}"
        pass: "{{userpass}}"
        policies: "{{username}}"
      register: 'vault_userpass_create'
      no_log: True
    - assert: { that: "{{vault_userpass_create.changed}} == True" }
    - assert: { that: "{{vault_userpass_create.rc}} == 0" }

    - hashivault_userpass:
        name: "delete_{{username}}"
        state: absent
      register: 'vault_userpass_delete'
    - assert: { that: "{{vault_userpass_delete.changed}} == True" }
    - assert: { that: "{{vault_userpass_delete.rc}} == 0" }

    - template:
        src: "{{playbook_dir}}/templates/userpassenv.sh.j2"
        dest: "{{playbook_dir}}/userpassenv.sh"
        mode: 0700
